import Heading from "../Heading/Heading";
import Process from "../Process/Process";

const InfoPage = ({ type }) => {
    if (type === "process") return <div className="pt-[12vh] md:pt-[14vh]"><Process /></div>;
    const isContact = type === "contact";
    return <div className="max-w-[1400px] mx-auto px-10 py-32"><Heading highlight={isContact ? "Contact" : "About"} heading={isContact ? "Us" : "Grosify"} /><div className="grid md:grid-cols-2 gap-12 mt-12 items-start"><div><h3 className="text-3xl font-bold text-zinc-800">{isContact ? "We are here to help" : "Fresh food, made simple"}</h3><p className="text-zinc-600 text-lg leading-relaxed mt-5">{isContact ? "Have a question about an order or a product? Send us a message and our team will get back to you shortly." : "Grosify connects everyday shoppers with carefully selected farm-fresh groceries. We believe better ingredients make better days, so we keep quality, freshness, and honest service at the center of every order."}</p><p className="text-zinc-600 text-lg leading-relaxed mt-5">{isContact ? "Email: hello@grosify.com | Phone: +1 555 012 3456" : "From seasonal produce to pantry staples, every item is chosen to make healthy shopping feel effortless."}</p></div>{isContact ? <form className="bg-zinc-100 rounded-xl p-7 space-y-5"><input required placeholder="Your name" className="w-full p-3 rounded-lg border border-zinc-300 focus:outline-orange-500" /><input required type="email" placeholder="Email address" className="w-full p-3 rounded-lg border border-zinc-300 focus:outline-orange-500" /><textarea required placeholder="How can we help?" rows="5" className="w-full p-3 rounded-lg border border-zinc-300 focus:outline-orange-500" /><button type="submit" className="bg-gradient-to-b from-orange-400 to-orange-500 text-white px-8 py-3 rounded-lg text-lg cursor-pointer">Send Message</button></form> : <div className="bg-zinc-100 rounded-xl p-8"><h4 className="text-2xl font-bold text-zinc-800">Our promise</h4><ul className="mt-6 space-y-4 text-zinc-600"><li>Fresh products sourced with care.</li><li>Clear pricing and dependable delivery.</li><li>Friendly support whenever you need it.</li></ul></div>}</div></div>;
};

export default InfoPage;
